### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dougefla**
Hello! I'd like to add a line into readme.

### CODE REVIEW

**Review by naba89 — CHANGES_REQUESTED** [review]
Great, could you add another line?

**Comment by dougefla** [comment]
Sure. But how can I add another line? Edit this pr or add another pr?

**Comment by naba89** [comment]
> Sure. But how can I add another line? Edit this pr or add another pr?

I think, you can just commit to your fork on the main branch and it will get update here.

**Comment by dougefla** [comment]
Thx! Updated, but with some conflicts :(

**Comment by naba89** [comment]
> Thx! Updated, but with some conflicts :(

I resolved the conflict and merged. Cheers!

**Comment by dougefla** [comment]
Cheers! Thx!

**Pull request merged**
